In [3]:
import pandas as pd

dataframe=pd.read_csv("/content/crop-recommendation.csv")

dataframe.head(5)

    N   P   K  temperature   humidity        ph    rainfall label
0  90  42  43    20.879744  82.002744  6.502985  202.935536  rice
1  85  58  41    21.770462  80.319644  7.038096  226.655537  rice
2  60  55  44    23.004459  82.320763  7.840207  263.964248  rice
3  74  35  40    26.491096  80.158363  6.980401  242.864034  rice
4  78  42  42    20.130175  81.604873  7.628473  262.717340  rice

In [4]:
dataframe.sample(5)

        N   P   K  temperature   humidity        ph    rainfall        label
935    26  18  42    19.726205  89.649342  6.910375  108.228728  pomegranate
2023   80  45  42    23.142650  74.997398  7.380396  151.903548         jute
2104  116  28  34    23.443723  60.395233  6.423211  122.210325       coffee
2060   79  45  43    25.719013  79.155324  7.171054  187.173542         jute
2093   63  47  35    26.985822  89.055879  7.432768  193.877871         jute